### ISSUE TITLE
Slack autoinvite

### ISSUE THREAD

**Issue by awrelll** [gov-ithub/govithub-auth-sso#14]
Salutare, 
Am vazut deja in doua locuri linkuri catre Slack dar nicio posibilitate de signup fara a fi invitat de o alta persoana.
Folositi cu incredere https://github.com/outsideris/slack-invite-automation

**Comment by timotei** [comment]
Hi,

Exista deja http://govitslack.herokuapp.com/

**Comment by ClaudiuCeia** [comment]
Am updatat README, o să fac și la celelalte proiecte, mersi de heads up.
